spring:
  application:
    name: auth-service

server:
  port: 8081
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: logfile,loggers,health,info
jwt:
  secret: ${JWT_SECRET:IQtVzYM/m2FFQ3xrD8QbF5+WgfxAiPoN9Fg77OYudbs=}
  expiration: ${JWT_EXPIRATION:86400000}

keycloak:
  realm: ${KEYCLOAK_REALM:graduation-realm}
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
  resource: ${KEYCLOAK_RESOURCE:auth-service}
  credentials:
    secret: ${KEYCLOAK_CREDENTIALS_SECRET:7lpM6koEjtcWRWdusYNfLV4oF+pK33LVnZcjjnv84vs=}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:auth-service-phofile-photos}
    region: ${AWS_S3_REGION:sa-east-1}
    access-key: ${AWS_S3_ACCESS_KEY:AKIAU3XM25VYWDOB6DFW}
    secret-key: ${AWS_S3_SECRET_KEY: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}
auth:
  persistence:
    provider: ${AUTH_PERSISTENCE_PROVIDER:keycloak}

resilience4j.circuitbreaker:
  instances:
    keycloak:
      slidingWindowSize: 5
      failureRateThreshold: 100
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED

logging:
  level:
    com:
      graduationparty:
        authservice: DEBUG
    org:
      springframework:
        security: DEBUG
    root: INFO
  file:
    name: application.log