spring:
  application:
    name: auth-service

server:
  port: 8081
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: logfile,loggers,health,info

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

keycloak:
  realm: ${KEYCLOAK_REALM}
  server-url: ${KEYCLOAK_SERVER_URL}
  resource: ${KEYCLOAK_RESOURCE}
  credentials:
    secret: ${KEYCLOAK_CREDENTIALS_SECRET}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_S3_REGION}
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}

auth:
  persistence:
    provider: ${AUTH_PERSISTENCE_PROVIDER}

resilience4j.circuitbreaker:
  instances:
    keycloak:
      slidingWindowSize: 5
      failureRateThreshold: 100
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED

logging:
  level:
    com:
      graduationparty:
        authservice: DEBUG
    org:
      springframework:
        security: DEBUG
    root: INFO
  file:
    name: application.log
