services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
    networks:
      - graduation-network

networks:
  graduation-network:
    external: true